
LmakeVectorBody:
        PUSH(FP);
        MOV(FP, SP);
        PUSH(R1);
        PUSH(R2);
        PUSH(R3);
        PUSH(R4);
        PUSH(R5);
        PUSH(R6);
        PUSH(R7);
        PUSH(R8);
        PUSH(R9);
        PUSH(R10);
        PUSH(R11);
        PUSH(R12);
        PUSH(R13);
        PUSH(R14);
  
  CMP(FPARG(1),IMM(2));
  JUMP_NE(L_error_incorrect_num_of_args);
  CMP(IND(FPARG(2)),IMM(T_INTEGER));
  JUMP_NE(L_error_incorrect_type);
  
  CMP(INDD(FPARG(2),1),IMM(0));
  JUMP_EQ(LmakeVectorBodyEmptyVector);
  MOV(R0,INDD(FPARG(2),1)); 
  MOV(R1,FPARG(3)); 
  MOV(R2,R0); 
  ADD(R2,IMM(1)); 
LmakeVectorBodyLoopStart:
  PUSH(R1);
  DECR(R0);
  CMP(R0,IMM(0));
  JUMP_NE(LmakeVectorBodyLoopStart);
LmakeVectorBodyLoopEnd:
  PUSH(INDD(FPARG(2),1));
  CALL(MAKE_SOB_VECTOR);
  DROP(R2);
  JUMP(LmakeVectorBodyExit);
LmakeVectorBodyEmptyVector:
  PUSH(IMM(0));
  CALL(MAKE_SOB_VECTOR);
  DROP(1);
  JUMP(LmakeVectorBodyExit);
LmakeVectorBodyExit:
        POP(R14);
        POP(R13);
        POP(R12);
        POP(R11);
        POP(R10);
        POP(R9);
        POP(R8);
        POP(R7);
        POP(R6);
        POP(R5);
        POP(R4);
        POP(R3);
        POP(R2);
        POP(R1);
        POP(FP);
        RETURN;